#!/bin/sh

# Push a dotfiles repo and sym link all data


dotpath="$HOME/repos/linux/dotfiles"

if [-d "$dotpath" ]
	sudo -u "$name" hub pull dotfiles "$dotpath"
else
	sudo -u "$name" mkdir -p "$HOME/repos/linux"
	sudo -u "$name" hub clone dotfiles "$dotpath"
fi

# TODO: remove existing

sudo -u "$name" stow -vt "$HOME" [a-z]*
